# 基础信息
title:              技术专栏
email:              mowchann@outlook.com
description:        
author:             MowChan
url:                "https://www.mowchan.me"
baseurl:            "/"
cdn_url:            "https://cdn.mowchan.me/image/column/"

# 插件
plugins:
  - jekyll-feed
  - jekyll-paginate

# 设置
markdown:           kramdown
timezone:           Asia/Shanghai
permalink:          "/post/:year/:slug.html"
paginate:           10
paginate_path:      "/archive/:num/"

# Markdown 格式配置
kramdown:
  math_engine: katex
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

# 网站数据统计
google_analytics:   UA-169011929-1

# 社交账号
twitter_username:   
github_username:    mowchann
facebook_username:  
linkedin_username:
