title:              MowChan技术专栏
email:              mowchann@outlook.com
description:        
author:             MowChan
baseurl:            "/"
cdn_url:  "https://cdn.mowchan.me/image/column/"
url:                "https://www.mowchan.me"

# Social Profiles
twitter_username:   
github_username:    mowchann
facebook_username:  
linkedin_username:

background_image: false

# Build settings
markdown:           kramdown
timezone:           Asia/Shanghai

kramdown:
  math_engine: katex
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false

paginate:           10
paginate_path:      "/archive/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /post/:year/:slug.html

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-169011929-1 # out your google-analytics code
